name: Deploy to PyPI

on:
  push:

env:
  TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
  TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup Python
      uses: actions/setup-python@v4.6.0
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools==58.2.0
        pip install --upgrade wheel twine

    - name: Build and upload
      run: |
        python setup.py sdist bdist_wheel
        twine upload --verbose dist/*.tar.gz
